### ISSUE TITLE
RT-AC87U - /jffs/startup.sh: readonly: line 9: SCRIPT_NAME: is read only

### ISSUE THREAD

**Issue by mihsu81** [jacklul/asuswrt-scripts#1]
Hi @jacklul,

When running `/bin/sh /jffs/startup.sh install` i get the following error: `/jffs/startup.sh: readonly: line 9: SCRIPT_NAME: is read only
`.

Thanks in advance for your help getting this issue fixed.

**Comment by jacklul** [comment]
So this is AC device so I think I can assume it will have older shell interpreter.
You might try modifying the scripts and remove any "readonly "  you can find.

**Comment by mihsu81** [comment]
That fixed it. Thanks a lot.
