### ISSUE TITLE
Add an ipsec.postconf custom config script

### ISSUE THREAD

**Issue by papypaprika** [jacklul/asuswrt-scripts#5]
Hi,

thank you very much for these extremely handy scripts.

how difficult would it be to add an ipsec.postconf custom config script?

thank you!!

**Comment by jacklul** [comment]
Actually it should be working, I just forgot to put it into readme
https://github.com/jacklul/asuswrt-scripts/blob/master/scripts/custom-configs.sh#L283

**Comment by papypaprika** [comment]
Ha fantastic, awesome thank you.
