### ISSUE TITLE
usb-mount  not  working

### ISSUE THREAD

**Issue by klcb2010** [jacklul/asuswrt-scripts#7]
On the Merlin 384 firmware, the AX600 does not automatically mount a USB drive during startup. After installing 'usb-mount,' I discovered that it was not working correctly because, even after rebooting the router, the USB drive still did not get mounted automatically. Here are the steps I followed in order:

1. I executed the command `curl -fsSL "https://mirror.ghproxy.com/https://raw.githubusercontent.com/jacklul/asuswrt-scripts/master/scripts-startup.sh" -o /jffs/scripts-startup.sh` and then ran `chmod +x /jffs/scripts-startup.sh`. Next, I executed `/jffs/scripts-startup.sh install`.

2. I used the command `curl -fsSL "https://mirror.ghproxy.com/https://raw.githubusercontent.com/jacklul/asuswrt-scripts/master/scripts/usb-mount.sh" -o /jffs/scripts/usb-mount.sh`.

3. I placed the `asusware.arm` folder at the root directory of the USB drive and restarted the router.

**Comment by jacklul** [comment]
1. Is there usb-mount entry in `cru l` ?
2. Are you able to mount the storage manually from ssh?

**Comment by klcb2010** [comment]
> Do not place asusware folder on the USB when using Merlin firmware, it's for the stock firmware only.
> 
>     1. Is there `usb-mount` entry in `cru l` output?
> 
>     2. Are you able to mount the storage manually from ssh?



> Do not place asusware folder on the USB when using Merlin firmware, it's for the stock firmware only.
> 
>     1. Is there `usb-mount` entry in `cru l` output?
> 
>     2. Are you able to mount the storage manually from ssh?

1.ye
2.no

**Comment by jacklul** [comment]
All this script does is run `mount` command, if you can't mount your storage manually using `mount /dev/your device /mint/yourmountpoint` then it won't work.

The script is targeted to fix issues where firmware stops mounting storage devices when there is different kind of USB device plugged in (or using USB hub), nothing more.
